### ISSUE TITLE
Updates post refactoring review

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/kaskadi-update-stocks-lambda#1]
because there is no PR yet, i'll comment here...

this is looking very good now!

**Comment by Holger-Will** [comment]
can we integrate the call to update `stock_last_updated` into the bulk call?
https://github.com/kaskadi/kaskadi-update-stocks-lambda/blob/0b87e9db27f3796637c99ec86257bd314e67c677/kaskadi-update-stocks-lambda.js#L16

**Comment by Holger-Will** [comment]
all naming should be camelCase to follow project conventions... so rename `stock_last_updated` to `stockLastUpdated`

**Comment by Holger-Will** [comment]
`getBulkBody` is a misleading name, maybe `createBulkBody` or `makeBulkBody` describes better what the function does..?

**Comment by alexlemaire** [comment]
Sorry for the PR, I didn't know that all commits would follow up anyway after creation so I handled it poorly!

I will update all that then

**Comment by alexlemaire** [comment]
Updated :+1:
